[args]
scriptsBlobPath = "{game_dir}\\r6\\cache\\modded\\final.redscripts"

[[tasks]]
command = "InvokeScc"
terminate_on_errors = false
no_window = true
template_args = ["-compile", "{path}", "-customCacheDir", "{custom_cache_dir}"]
substitutions.path = "{game_dir}/r6/scripts"
substitutions.custom_cache_dir = "{game_dir}/r6/cache/modded"
